
get http://localhost:3000/notes

### 

get http://localhost:3000/notes/1

### 
put http://localhost:3000/notes/2
Content-Type: application/json

{
  "title": "Note 002 atualizado",
  "body": "Body note"
}

### 
delete http://localhost:3000/notes/3

### 

post http://localhost:3000/notes
Content-Type: application/json

{
  "title": "Note 002",
  "body": "Body note"
}