
get http://localhost:3000/api/notes

### 

get http://localhost:3000/api/notes/1

###

post http://localhost:3000/api/notes
Content-Type: application/json

{
  "title": "Note 002",
  "body": "Body note"
}

### 
put http://localhost:3000/api/notes/2
Content-Type: application/json

{
  "title": "Note 002 atualizado",
  "body": "Body note"
}

### 
delete http://localhost:3000/api/notes/3

### 

